config/routes.rb
Demo::Application.routes.draw do
  authenticated :user do
    root :to => 'starts#index', :as => :unauthenticated_path
  end

  devise_scope :user do
    root :to => "devise/sessions#new", :as => :authenticated_path
  end

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  resources :patients  
  resources :patient_searches
  resources :homes
  resources :starts

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
	 :confirmable, :lockable, :timeoutable 
  attr_accessible :email, :password, :password_confirmation
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  self.table_name = "patients"
end

app/models/patient_search.rb
class PatientSearch < ActiveRecord::Base
  self.table_name = "patient_searches"
  def patients
    @patients ||= find_patients
  end

private

  def find_patients
    patients = Patient.order(:id)
    patients = patients.where(drc_id: drc_id) if drc_id.present?
    patients = patients.where(first_initial: first_initial) if first_initial.present?
    patients = patients.where(last_initial: last_initial) if last_initial.present?
    patients
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users
end

app/models/start.rb
class Start < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :role
	before_create :set_default_role

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	attr_accessible :email, :password, :password_confirmation

	private
	def set_default_role
		self.role ||= Role.find_by_name('researcher')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patient_searches_controller.rb
class PatientSearchesController < ApplicationController
  def new
    @search = PatientSearch.new
  end

  def create
    @search = PatientSearch.create! (params[:search])
    redirect_to @search
  end

  def show
    @search = PatientSearch.find(params[:id])
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render action: 'show', status: :created, location: @patient }
      else
        format.html { render action: 'new' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params[:patient]
    end
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  devise_for :users, skip: :registrations
  devise_scope :user do
    resource :registration,
	    only: [:new, :create, :edit, :update],
	    path: 'users',
	    path_names: { new: 'sign_up' },
	    controller: 'devise/registrations',
	    as: :user_registration do
	      get :cancel
	    end
	
  end

	protected

	def after_sign_up_path_for('starts')
		after_sign_up_path_for(:starts)
	end

  def after_sign_in_path_for('starts')
    after_sign_in_path_for(:starts)
  end

  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patient_searches_helper.rb
module PatientSearchesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/starts_helper.rb
module StartsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
	<link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="/">Demo DRC App</a>
			<ul class="nav">
				<li class="active"><a href="/patients">Patients</a>
			</ul>
		<p class="navbar-text pull-right">
		<% if user_signed_in? %>
			Logged in as <strong><%= current_user.email %></strong>
			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
		<% else %>
			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
			<%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
		<% end %>
		</div>
	</div>
</div>

<div class="container">
	<% if notice %>
		<p class="alert alert-notice"><%= notice %></p>
	<% end %>
	<% if alert %>
		<p class="alert alert-error"><%= alert %></p>
	<% end %>
	<%= yield %>
</div>

<footer>
	<div class="container">
		Jacalyn Macfarlane, DRC, 2013
	</div>
</footer>

</body>
</html>

app/views/patient_searches/new.html.erb
<h1>Patient Search</h1>

<%= form_for @search do |f| %>
  <div clas"field">
    <%= f.label :drc_id %><br />
    <%= f.text_field :drc_id %>
  </div>
  <div class="field">
    <%= f.label :first_initial %><br />
    <%= f.text_field :first_initial %>
  </div>
  <div class="field">
    <%= f.label :last_initial %><br />
    <%= f.text_field :last_initial %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

app/views/patient_searches/show.html.erb
<h1>Search Results</h1>

<%= render @search.patients %>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
				<td><%= patient.first_initial %></td>
				<td><%= patient.last_initial %></td>
				<td><%= patient.created_at %></td>
				<td><%= patient.id %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/starts/index.html.erb
<h1>Welcome to the DRC database</h1>

<p><%= link_to "Patient Search", new_patient_search_path %></p>